# Generated by Django 3.1.1 on 2020-09-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_sentences', models.TextField()),
                ('preposition', models.CharField(choices=[('about', 'about'), ('above', 'above'), ('across', 'across'), ('after', 'after'), ('afterward', 'afterward'), ('against', 'against'), ('ago', 'ago'), ('among', 'among'), ('apart', 'apart'), ('around', 'around'), ('as', 'as'), ('at', 'at'), ('atop', 'atop'), ('away', 'away'), ('back', 'back'), ('before', 'before'), ('behind', 'behind'), ('below', 'below'), ('besides', 'besides'), ('between', 'between'), ('beyond', 'beyond'), ('but', 'but'), ('by', 'by'), ('circa', 'circa'), ('despite', 'despite'), ('down', 'down'), ('downstairs', 'downstairs'), ('during', 'during'), ('except', 'except'), ('for', 'for'), ('from', 'from'), ('home', 'home'), ('in', 'in'), ('indoors', 'indoors'), ('inside', 'inside'), ('into', 'into'), ('like', 'like'), ('minus', 'minus'), ('near', 'near'), ('nearby', 'nearby'), ('of', 'of'), ('off', 'off'), ('on', 'on'), ('onto', 'onto'), ('out', 'out'), ('outside', 'outside'), ('over', 'over'), ('past', 'past'), ('per', 'per'), ('plus', 'plus'), ('round', 'round'), ('since', 'since'), ('than', 'than'), ('through', 'through'), ('throughout', 'throughout'), ('till', 'till'), ('to', 'to'), ('together', 'together'), ('toward', 'toward'), ('under', 'under'), ('unlike', 'unlike'), ('until', 'until'), ('up', 'up'), ('upon', 'upon'), ('via', 'via'), ('with', 'with'), ('within', 'within'), ('without', 'without')], max_length=999)),
                ('results', models.TextField()),
                ('description', models.TextField()),
                ('submitted_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('PND', 'Pending'), ('CMP', 'Complete')], default='PND', max_length=3)),
            ],
        ),
    ]
