# Generated by Django 3.1.1 on 2020-09-13 18:50

import bcs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_sentences',
            field=bcs.models.ListField(token=','),
        ),
    ]
