# Generated by Django 3.1.1 on 2020-09-13 18:56

import bcs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0002_auto_20200913_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_sentences',
            field=bcs.models.ListField(token='熕'),
        ),
    ]
