# Generated by Django 3.1.1 on 2020-10-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0003_auto_20200913_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='preposition',
        ),
    ]
